language: php

sudo: false

php:
  - 7.1
  - 7.2

env:
  global:
    - DB_BITRIX_HOST=localhost
    - DB_BITRIX_LOGIN=root
    - DB_BITRIX_PASS=root
    - DB_BITRIX_NAME=bitrix
    - BITRIX_PATH=$TRAVIS_BUILD_DIR/bitrix

before_script:
  # Change MySQL root password
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

  - composer install
  - bash tests/bin/before_script.sh

script:
  - make test
